final List<Map<String, dynamic>> recipes = [
  {
    'id': 1,
    'image': 'https://luigispizzakenosha.com/wp-content/uploads/placeholder.png',
    'title': 'Spaghetti Carbonara',
    'category': 'MainDish',
    'chef': 'Chef Mari',
    'calories': 600,
    'likes': 120,
    'rating': 4.5,
    'isFavorite': true,
  },
  {
    'id': 2,
    'image': 'https://luigispizzakenosha.com/wp-content/uploads/placeholder.png',
    'title': 'Caesar Salad',
    'category': 'Salad',
    'chef': 'Chef Anna',
    'calories': 300,
    'likes': 85,
    'rating': 4.0,
    'isFavorite': false,
  },
  {
    'id': 3,
    'image': 'https://luigispizzakenosha.com/wp-content/uploads/placeholder.png',
    'title': 'Chocolate Cake',
    'category': 'Dessert',
    'chef': 'Chef Clara',
    'calories': 450,
    'likes': 200,
    'rating': 4.8,
    'isFavorite': true,
  },
  {
    'id': 4,
    'image': 'https://luigispizzakenosha.com/wp-content/uploads/placeholder.png',
    'title': 'Green Smoothie',
    'category': 'Smoothies',
    'chef': 'Chef John',
    'calories': 150,
    'likes': 60,
    'rating': 4.3,
    'isFavorite': false,
  },
  {
    'id': 5,
    'image': 'https://luigispizzakenosha.com/wp-content/uploads/placeholder.png',
    'title': 'Grilled Chicken',
    'category': 'Main Dish',
    'chef': 'Chef Alex',
    'calories': 500,
    'likes': 150,
    'rating': 4.6,
    'isFavorite': true,
  },
];